### ISSUE TITLE
Int Parse issue

### ISSUE THREAD

**Issue by F9Alejandro** [F9Alejandro/BBreaker#2]
# **Error Report**
**Plugin Version:** 1.0.8-SNAPSHOT
**Server Version:** 1.8
**Server Name:** LocalHost (Test Server)

### **Issue**

Issue parsing the server version to int
### **When does the issue occur**

/bbreak ench [1-3]
### **Expected**

Enchant the item held (pickaxe) with custom Silky Fortune Enchant [I-III]
**Stack-trace**

```
[06:54:24 INFO]: Fang_Shadow issued server command: /bbreak ench 3
[06:54:24 INFO]: 1.80.1
[06:54:24 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bbreak' in plugin BBreaker v1.0.8
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.jar:git-Spigot-550ebace-7019900e]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.jar:git-Spigot-550ebace-7019900e]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.8.jar:git-Spigot-550ebace-7019900e]
	at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
	at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_152]
	at java.lang.Integer.parseInt(Integer.java:592) ~[?:1.8.0_152]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_152]
	at me.Fang.BBreaker.util.BBUtil.getVer(BBUtil.java:150) ~[?:?]
	at me.Fang.BBreaker.util.Item.getItemMainHand(Item.java:71) ~[?:?]
	at me.Fang.BBreaker.util.InventoryHandler.setEnch(InventoryHandler.java:111) ~[?:?]
	at me.Fang.BBreaker.Main.onCommand(Main.java:150) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.jar:git-Spigot-550ebace-7019900e]
	... 14 more
```

**Comment by F9Alejandro** [comment]
Should be fixed in final 1.0.8 out of beta version. Will allow use with pre 1.9 combat update servers
